server:
  port: 5050

management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true

spring:
  cloud:
    gateway:
      routes:
        - id: account-server
          uri: http://account-server:8080
          predicates:
            - Path=/api/account/**
        - id: core-server
          uri: http://core-server:9090
          predicates:
            - Path=/api/admin/**
            - Path=/api/music/**