server:
  port: 5050

management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true

spring:
  cloud:
    gateway:
      routes:
        - id: account-server
          uri: http://localhost:8080
          predicates:
            - Path=/api/account/**
        - id: music-service-server-socket
          uri: http://localhost:9090
          predicates:
            - Path=/ws-endpoint/**
        - id: music-service-server
          uri: http://localhost:9090
          predicates:
            - Path=/api/admin/**,/api/music/**
        - id: file-server
          uri: http://localhost:6060
          predicates:
            - Path=/api/file/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost"
              - "http://localhost:3000"
              - "http://127.0.0.1"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
